name: Auto Commit with Python

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecuta cada 5 minutos
  workflow_dispatch:       # Permite ejecución manual

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configure Git with user info
        run: |
          git config user.name "majopan"
          git config user.email "mariazzz2326@gmail.com"

      - name: Run Python script
        run: python auto_commit.py
